### ISSUE TITLE
Request: Adding the created and updated tags to the note metadata

### ISSUE THREAD

**Issue by kraibse** [PaulTreanor/notes-dater#1]
The plugin works well but I would like to have in my notes metadata as well so I could query it with Dataview.

Thank you in advance.

**Comment by PaulTreanor** [comment]
Hi @kraibse,
Thank you for taking the time to submit this feature request. 

I considered this approach when I was making the plugin but I couldn't make it work because writing metadata is updating the note. This would mean the `updated_on` time of all notes would be set to the date that you installed the plugin. This is why I chose to display the dates in the status bar instead. 

Sorry about this,
Paul

**Comment by kraibse** [comment]
As far as I know they reworked their frontmatter code in the last updates. You could check for the FrontmatterCache and if it has changed at all after a debounce if that isn't already in there.
