### ISSUE TITLE
Store the created/updated info in a note's properties

### ISSUE THREAD

**Issue by ahoebeke** [PaulTreanor/notes-dater#2]
Hi :-)
I would like for this info to be stored in the properties (frontmatter) of notes.

It would be simple to do so, if you think it's ok for your plugin to add this feature.

```
		await view.app.fileManager.processFrontMatter(view.file, (frontmatter: { created_on?: string; updated_on?: string }) => {
			if (!frontmatter.created_on) {
                                   frontmatter.created_on = "<date>"; // TODO set value
			}

			if (frontmatter.updated_on !== updatedOnValue)
				frontmatter.updated_on = "<date>"; // TODO set value
		});
```

Something like this is all you'd need :-)

**Comment by PaulTreanor** [comment]
Hi @ahoebeke, 
Thanks for the suggestion. I understand the interest in having a feature that edits the file's frontmatter, but I haven't added this feature because this would involve the plugin editing every file in the vault. 

I'm avoiding changes that would automatically update files as that would irreversibly change the "updated-on" value of each note to be the date that notes-dater was installed on, rather than the last date that the note was actually modified by the user. The current approach of just reading file meta-data and displaying it outside of the core note UI preserves the original file date meta-data. 

That being said, I'm open to further discussions and ideas. There seems to be interest in addressing this issue so I'm going to leave this issue as open. 
Best regards,
Paul

**Comment by ahoebeke** [comment]
Ah nice! Clear explanation and indeed good reason!
Right now it's not of utmost importance to me ;-) so won't press further.
Thing that comes to mind is auto-updating the frontmatter as soon as a note
is updated, but I can't judge how useful or helpful that would be.

Will leave that thought here. I may circle back, or see whom else comes
along with ideas :-)
Thank you for leaving it open!
Best regards

**Comment by nicolnt** [comment]
I adapted the plugin to do the contrary #5 

Basically, I use a combination of [obsidian-linter](https://github.com/platers/obsidian-linter) and [obsidian-frontmatter-modified-date](https://github.com/alangrainger/obsidian-frontmatter-modified-date) as described in [this Obsidian forum post](https://forum.obsidian.md/t/handle-file-creation-date-modified-date-internally-dont-use-the-filesystem-info/26148/15?u=nicolas.lienart).

Then the notes-datter plugin can use these properties instead of relying on filesystem date and time information, which can be easily broken without actually changing the note itself…

![image](https://github.com/PaulTreanor/notes-dater/assets/12377588/5c6e9003-0663-40a0-a247-a7614caeef8e)

**Comment by PaulTreanor** [comment]
Hi @nicolnt thanks so much for making this PR, I think it will make the plugin work better for more people.

I'm going to try to understand the changes fully before I merge the PR but I respond within a day or two. I had no idea that filesystem dates had these problems so this is a good lesson for me.

**Comment by PaulTreanor** [comment]
Merged changes required for this features
